[workspace]

members = [
    "ros",
    "remu",
    "ram",
    "rapps",
    "rconfig",
]

resolver = "2"

[workspace.package]
authors = ["Qi Zhan <qizhan@zju.edu.cn>"]
description = "Emulating computer system in Rust"
repository = "https://github.com/Qi-Zhan/SysR"

[profile.release]
debug = true
